### ISSUE TITLE
fatal compiler error on swift 5.7 and Swift 5.8

### ISSUE THREAD

**Issue by sebsto** [swiftlang/swift-docc#1016]
### Description

using Swift Docc plugin 1.0.0, I receive fatal compilation error from Swift on 5.7 and 5.8

```
19:03:38 [2/2] Compiling plugin Swift-DocC
19:03:38 error: fatalError
```
or
```
19:01:05 Compiling plugin Swift-DocC...
19:01:05 error: emit-module command failed with exit code 1 (use -v to see invocation)
19:01:05 /code/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Convert/Symbolic Links/SwiftDocCPluginUtilities/CommandLineArguments/CommandLineArguments.swift:31:50: error: consecutive declarations on a line must be separated by ';'
19:01:05     private var remainingOptionsOrFlags: [String].SubSequence
19:01:05                                                  ^
19:01:05                                                  ;
19:01:05 /code/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Convert/Symbolic Links/SwiftDocCPluginUtilities/CommandLineArguments/CommandLineArguments.swift:31:50: error: expected declaration
19:01:05     private var remainingOptionsOrFlags: [String].SubSequence
19:01:05                                                  ^
19:01:05 /code/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Convert/Symbolic Links/SwiftDocCPluginUtilities/CommandLineArguments/CommandLineArguments.swift:12:15: note: in declaration of 'CommandLineArguments'
19:01:05 public struct CommandLineArguments {
19:01:05               ^
19:01:05 /code/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Convert/Symbolic Links/SwiftDocCPluginUtilities/CommandLineArguments/CommandLineArguments.swift:34:40: error: consecutive declarations on a line must be separated by ';'
19:01:05     private var literalValues: [String].SubSequence
19:01:05                                        ^
19:01:05                                        ;
19:01:05 /code/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Convert/Symbolic Links/SwiftDocCPluginUtilities/CommandLineArguments/CommandLineArguments.swift:34:40: error: expected declaration
19:01:05     private var literalValues: [String].SubSequence
19:01:05                                        ^
19:01:05 /code/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Convert/Symbolic Links/SwiftDocCPluginUtilities/CommandLineArguments/CommandLineArguments.swift:12:15: note: in declaration of 'CommandLineArguments'
19:01:05 public struct CommandLineArguments {
19:01:05               ^
19:01:05 error: fatalError
```

This breaks our pipeline for The Swift Lambda runtime, see the automated tests for this PR : https://github.com/swift-server/swift-aws-lambda-runtime/pull/342

### Checklist

- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

Should compile on last 3 Swift versions 

### Actual behavior

```
error: fatalError
```

### Steps To Reproduce

Checkout this PR and compile with a 5.7 or 5.8 toolchain

### Swift-DocC Version Information

1.0.0

### Swift Compiler Version Information

```shell
5.7 and 5.8
```

**Comment by d-ronnqvist** [comment]
I'm on vacation next week, away from a computer, but I can look at this when I get back if no one else has fixed this by then.

**Comment by d-ronnqvist** [comment]
That makes no sense since [the file that those errors are about][file] is 1 day old and [the 1.3.0 release][release] is from June 2023

[file]: https://github.com/swiftlang/swift-docc-plugin/blob/main/Sources/SwiftDocCPluginUtilities/CommandLineArguments/CommandLineArguments.swift
[release]: https://github.com/swiftlang/swift-docc-plugin/releases/tag/1.3.0

**Comment by sebsto** [comment]
Here is the PR where I observed the error. It looks like the latest version is picked up because of the `from`

The `Package@swift-5.7.swift`, `Package@swift-5.8.swift`, and `Package.swift`,
have all this dependency
```
.package(url: "https://github.com/apple/swift-docc-plugin", from: "1.3.0")
```

This is the error from [Jenkins logs for Swift 5.7 ](https://ci.swiftserver.group/job/swift-aws-lambda-runtime-swift57-prb/208/console)
```
Compiling plugin Swift-DocC...
19:59:10 error: emit-module command failed with exit code 1 (use -v to see invocation)
19:59:10 /code/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Convert/Symbolic Links/SwiftDocCPluginUtilities/CommandLineArguments/CommandLineArguments.swift:31:50: error: consecutive declarations on a line must be separated by ';'
19:59:10     private var remainingOptionsOrFlags: [String].SubSequence
19:59:10                                                  ^
19:59:10                                                  ;
19:59:10 /code/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Convert/Symbolic Links/SwiftDocCPluginUtilities/CommandLineArguments/CommandLineArguments.swift:31:50: error: expected declaration
19:59:10     private var remainingOptionsOrFlags: [String].SubSequence
19:59:10                                                  ^
19:59:10 /code/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Convert/Symbolic Links/SwiftDocCPluginUtilities/CommandLineArguments/CommandLineArguments.swift:12:15: note: in declaration of 'CommandLineArguments'
19:59:10 public struct CommandLineArguments {
19:59:10               ^
19:59:10 /code/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Convert/Symbolic Links/SwiftDocCPluginUtilities/CommandLineArguments/CommandLineArguments.swift:34:40: error: consecutive declarations on a line must be separated by ';'
19:59:10     private var literalValues: [String].SubSequence
19:59:10                                        ^
19:59:10                                        ;
19:59:10 /code/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Convert/Symbolic Links/SwiftDocCPluginUtilities/CommandLineArguments/CommandLineArguments.swift:34:40: error: expected declaration
19:59:10     private var literalValues: [String].SubSequence
19:59:10                                        ^
19:59:10 /code/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Convert/Symbolic Links/SwiftDocCPluginUtilities/CommandLineArguments/CommandLineArguments.swift:12:15: note: in declaration of 'CommandLineArguments'
19:59:10 public struct CommandLineArguments {
19:59:10               ^
19:59:10 error: fatalError
```

This is the error from [Jenkins logs for Swift 5.8 ](https://ci.swiftserver.group/job/swift-aws-lambda-runtime-swift58-prb/93/console)
```
19:59:21 [2/2] Compiling plugin Swift-DocC
19:59:21 error: fatalError
```

I'll force using the 1.3.0 version and report back

**Comment by sebsto** [comment]
My bad, SPM was picking up the latest version (1.4.1) - I forced the exact 1.3.0 version and this solves the problem. 
I updated the original description to mention plugin version 1.4.1
